apiVersion: v1
data:
  application.yml: |
    server:
      port: 7091
      maxSession: 20000
      netty:
        boss-thread-prefix: NettyBoss
        worker-thread-prefix: NettyServerNIOWorker
        server-worker-threads: 16
        boss-thread-size: 4
        max-connections: 20000
        write-buffer-high-water-mark: 67108864
        write-buffer-low-water-mark: 33554432

    spring:
      application:
        name: seata-server

    logging:
      config: classpath:logback-spring.xml
      file:
        path: ${log.home:${user.home}/logs/seata}
      extend:
        logstash-appender:
          destination: 127.0.0.1:4560
        kafka-appender:
          bootstrap-servers: 127.0.0.1:9092
          topic: logback_to_logstash

    console:
      user:
        username: seata
        password: seata

    seata:
      config:
        type: file
      registry:
        type: file
      store:
        mode: redis
        redis:
          mode: single
          single:
            host: redis
            port: 6379
          password: ""
          database: 0
          min-conn: 50
          max-conn: 2000
          max-total: 2000
          query-limit: 10000
          max-idle: 100
          min-idle: 25
          max-wait: 1000
      server:
        service-port: 8091
        max-commit-retry-timeout: 10000
        max-rollback-retry-timeout: 10000
        rollback-retry-timeout-unlock-enable: false
        distributed-lock-expire-time: 10000
        xid-expire-time: 10000
        default-global-transaction-timeout: 60000
        enable-check-auth: true
        retry-dead-threshold: 130000
      security:
        secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
        tokenValidityInMilliseconds: 1800000
        csrf-ignore-urls: /metadata/v1/**
        ignore:
          urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login,/version.json,/health,/error,/vgroup/v1/**
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: seata-server
  name: seata-server-cm0
  namespace: seata-cluster