apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: seata-server-monitor
  namespace: seata-cluster
  labels:
    app: seata-server
spec:
  selector:
    matchLabels:
      io.kompose.service: seata-server
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter-monitor
  namespace: seata-cluster
  labels:
    app: redis-exporter
spec:
  selector:
    matchLabels:
      app: redis-exporter
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics